name: Copy file

on:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub

env:
  FILE_TO_COPY: "test_file.txt"

jobs:
  create-file:
    runs-on: ubuntu-latest
    outputs:
      # Define an output for this job
      file_to_copy_output: ${{ steps.set-filename.outputs.file_to_copy }}

    steps:
      - name: Checkout current repository (Repository A)
        uses: actions/checkout@v4 # Usa la versione più recente

      # Simula la creazione di un file da caricare.
      - name: Create example file to upload
        run: |
          echo "File coming from ${{ github.repository }}" > $FILE_TO_COPY
          echo "Data e ora: $(date)" >> $FILE_TO_COPY
          ls -lah

      # Set the output variable from the environment variable
      - name: Set filename output
        id: set-filename # Give this step an ID
        run: echo "file_to_copy=${{ env.FILE_TO_COPY }}" >> $GITHUB_OUTPUT

  copy-file-to-another-repo:
    needs: [create-file]
    uses: Neomediatech/docker-images-scan-reports/.github/workflows/copy-file-to-another-repo.yml@main
    with:
      filename: ${{ needs.create-file.outputs.file_to_copy_output }}
      #  run: echo "filename ${{ needs.create-file.vars.outputs.file_to_copy }}"
