name: Copy file

on:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub

jobs:
  copy-file-to-another-repo:
    uses: Neomediatech/docker-images-scan-reports/.github/workflows/copy-file-to-another-repo.yml@main
