name: Docker build and publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  #schedule:
  #  - cron: '31 21 * * *'
  #push:
  #  branches: [ "main" ]
  #  # Publish semver tags as releases.
  #  tags: [ 'v*.*.*' ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub
  workflow_call: # Permette di riutilizzare il workflow da un altro repo

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-scan-publish:
    uses: Neomediatech/docker-images-scan-reports/.github/workflows/build-and-scan-docker-image.yml@main

    #uses: Neomediatech/docker-images-scan-reports/.github/workflows/copy-file-to-another-repo.yml@main

