name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up image tag (lowercase)
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "tag=ghcr.io/${REPO_LOWER}:latest" >> $GITHUB_OUTPUT
          #echo "tag=ghcr.io/${REPO_LOWER}:${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Set INPUT_IMAGE_REF
        run: echo "INPUT_IMAGE_REF=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV

      - name: Echo the generated image tag
        run: echo "Attempting to scan image $INPUT_IMAGE_REF"

      - name: echo to file
        run: echo "blah blah blah" > test.txt

      - name: show dir content
        run: ls -lah ; pwd ; echo $GITHUB_WORKSPACE ; echo $RUNNER_TEMP

  copy-file-to-another-repo:
    uses: Neomediatech/docker-images-scan-reports/.github/workflows/copy-file-to-another-repo.yml@main
