name: Tests

on:
  push:
    branches: [main]
  pull_request:

env:
  REPO_LOWER: $(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
  INPUT_IMAGE_REF: ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):latest

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up image tag (lowercase)
        id: vars
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "tag=ghcr.io/${REPO_LOWER}:latest" >> $GITHUB_OUTPUT
          #echo "tag=ghcr.io/${REPO_LOWER}:${{ github.sha }}" >> $GITHUB_OUTPUT

      #- name: Build Docker image
      #  run: docker build -t ${{ steps.vars.outputs.tag }} .

      #- name: Push Docker image to GHCR
      #  run: docker push ${{ steps.vars.outputs.tag }}

      - name: Echo the generated image tag
        run: echo "Attempting to scan image $INPUT_IMAGE_REF"
